---
- hosts: localhost
  gather_facts: false
  become: no
  tasks:
    - name: Hosts | populate inventory into hosts file
      blockinfile:
        path: /etc/hosts
        block: |-
          {% for item in (groups['ceph-mon'] + groups['ceph-osd']|default([]))|unique -%}
          {% if 'access_ip' in hostvars[item] or 'ip' in hostvars[item] != "skip" -%}
          {{ hostvars[item]['access_ip'] | default(hostvars[item]['ip'])}}
          {%- if ('ansible_hostname' in hostvars[item] and item != hostvars[item]['ansible_hostname']) %} {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}{% endif %} {{ item }}
          {% endif %}
          {% endfor %}
        state: present
        create: yes
        backup: yes
        unsafe_writes: yes
        marker: "# Ansible inventory hosts {mark}"
  vars:
    ansible_connection: local

- hosts: localhost
  gather_facts: false
  become: no
  roles:
    - ceph-mon
    - ceph-osd

- hosts: ceph-osd[0] 
  gather_facts: false
  tasks:
    - name: fix ceph issue 
      shell: ceph osd crush tunables hammer 
      args:
        chdir: /home/ubuntu
        executable: /bin/bash

