kind: Secret
apiVersion: v1
metadata:
  name: ceph-admin-secret
type: "kubernetes.io/rbd"
data:  
  # on any Ceph node: sudo ceph auth get-key client.admin | base64  
  key: QVFDRG4yOWRqRlp1SWhBQTB2UU53M1hhK3lPbmphWVE5V252MlE9PQ==
 
