kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: xfs
provisioner: ceph.com/rbd  # must match with created provisioner name
parameters: 
  monitors: 10.100.0.22:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: default
  adminSecretName: ceph-admin-secret
  userId: kube
  userSecretNamespace: default
  userSecretName: ceph-secret
  imageFormat: "2" 
  imageFeatures: layering   
  fsType: xfs
allowVolumeExpansion: true
