---
kind: Secret
apiVersion: v1
metadata:
  name: ceph-secret
type: "kubernetes.io/rbd"
data:  
  # on any Ceph node: sudo ceph auth get-key client.kube | base64
  key: QVFEYm9HOWRyL3VoTUJBQWVHcW9zWGxZdmo4WEpsQjV6WElUb2c9PQ==
 
