kind: Role
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: rbd-provisioner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
--- 
kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: rbd-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbd-provisioner
subjects:
  - kind: ServiceAccount
    name: rbd-provisioner
    namespace: default
