kind: Secret
apiVersion: v1
metadata:
  name: ceph-admin-secret
type: "kubernetes.io/rbd"
data:
  # on any Ceph node: sudo ceph auth get-key client.admin | base64
  key: QVFBTjJtUmQrM3UyQ0JBQTVodk4xazg1c3BtemZRb3pSM0FialE9PQ==
---
kind: Secret
apiVersion: v1
metadata:
  name: ceph-secret
type: "kubernetes.io/rbd"
data:
  # on any Ceph node: sudo ceph auth get-key client.kube | base64
  key: QVFDRzZtUmRnZHhyRlJBQW5JdCtnM3VzeU91YUREaHpMNXdrb3c9PQ==
